name: tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - uses: actions/checkout@v1
    
    - name: Verify formatting
      run: /home/runner/.deno/bin/deno fmt --check

    - name: Run linter
      run: /home/runner/.deno/bin/deno lint

    - name: Run tests (stable)
      run: /home/runner/.deno/bin/deno test

    - name: Run tests (unstable)
      run: /home/runner/.deno/bin/deno test --unstable
